services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: hr-test
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: