FROM node:22-alpine as build

WORKDIR /app

COPY ./app/package*.json ./

RUN npm install


COPY app .
COPY .env .

RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY containers/app/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
