FROM node:22-alpine as build

WORKDIR /app

COPY ./app/package*.json ./

RUN npm install

COPY ./app /app

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./app/nginx.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
